name: Main Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QcademyMailUsername: ${{ secrets.QcademyMailUsername }}
      QcademyMailPassword: ${{ secrets.QcademyMailPassword }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up environment variables
        run: |
          echo "QcademyMailUsername=${QcademyMailUsername}" >> $GITHUB_ENV
          echo "QcademyMailPassword=${QcademyMailPassword}" >> $GITHUB_ENV

      - name: Print email username and password
        run: |
          echo "Email Username: $QcademyMailUsername"
          echo "Email Password: $QcademyMailPassword"

      - name: Build with Maven
        run: mvn -f backend/pom.xml clean install

      - name: Run Tests and Generate Coverage Report
        run: mvn -f backend/pom.xml clean test jacoco:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/target/site/jacoco/jacoco.xml
