name: Main Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QCADEMY_MAIL_USERNAME: ${{ secrets.QcademyMailUsername }}
      QCADEMY_MAIL_PASSWORD: ${{ secrets.QcademyMailPassword }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up environment variables
        run: |
          echo "QCADEMY_MAIL_USERNAME=${QCADEMY_MAIL_USERNAME}" >> $GITHUB_ENV
          echo "QCADEMY_MAIL_PASSWORD=${QCADEMY_MAIL_PASSWORD}" >> $GITHUB_ENV

     - name: Debugging Step
       run: |
          echo "Email Username: $QCADEMY_MAIL_USERNAME"
          echo "Email Password: $QCADEMY_MAIL_PASSWORD"
          exit 1  # This step intentionally fails to stop the workflow

     - name: Continue Workflow
       if: always()
       run: echo "The workflow continues..."



      - name: Build with Maven
        run: mvn -f backend/pom.xml clean install

      - name: Run Tests and Generate Coverage Report
        run: mvn -f backend/pom.xml clean test jacoco:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/target/site/jacoco/jacoco.xml
